# Optional: Enable info logging for the AC component
logger:
  default: error
  #logs:
    #custom_components.climate.gree: info # not sure if this works in HASSIO 0.88.0+ (untested)

climate: !include climate.yaml